module_metadata:
  aws_service : "key_pairs"
  module_dir  : "modules/aws/key_pairs"
  name        : ???
  state_file  : ???

config:
  key_name    : ???
  public_key  : ???
  owner       : "Hunter-Labs"

lookups: