module_metadata:
  aws_service : "ec2"
  module_dir  : "modules/aws/ec2"
  name        : ???
  state_file  : ???


config:
  # SG Config
  sg_name                     : ???
  sg_description              : ???
  ingress_cidr_blocks         : ???
  ingress_rules               : ???

  # EC2 Config
  instance_count              : 1
  instance_name               : ???
  associate_public_ip_address : False
  aws_account                 : ${build.aws_accounts[${build.environment}]}


lookups:
  key_pair_statefile  : ???
  vpc_statefile       : ???
