# Defaults defines how the final config object is composed.  Order is important terravarmer will create infra in
# specified order specified in defaults object
defaults:
  # Apps
  - aws/apps/serverless@app.lambda.hello_world_lambda: hello_world_lambda
  - aws/apps/serverless@app.api_gateway.hello_world_api: hello_world_api


# Environment specific config lives here
environment:
  prod:
    region: "us-east-1"
    profile: "<YOUR-PROFILE-HERE>"
    bucket: "<YOUR-BUCKET-HERE>"
  dev:
    region: "us-east-1"
    profile: "<YOUR-PROFILE-HERE>"
    bucket: "<YOUR-BUCKET-HERE>"



# Build section controls how the modules we defined are built
build:
  cloud_provider: "AWSProvider"  # Provider used to create all infra
  environment: "prod"            # Deployment environment must be one of dev|test|ppe|prod
  infra_shared: "create"         # Process shared infra, Must be one of create|destroy|pass
  infra_app: "create"            # Process application infra, must be one of create|destroy|pass
  terraform_mode: "apply"         # Must be one of plan|apply - Plan produces terraform plan only, apply will create or destroy infra
  debug: True                      # Set to True to enable verbose debugging
