# Lambda function that GeoCodes Scottish Government COVID data
defaults:
  - /aws/base/lambda@: lambda_base

module_metadata:
  name        : "terragen_hello"
  state_file  : "apps/terragen_hello/terraform.tfstate"


config:
  function_name          : "terragen_hello"
  function_description   : "Terragen Hello World Serverless"
  handler                : "hello_world.lambda_handler"
  timeout                : 10
  source_path            : "/tools/terraform/utils/terragen-hunter-labs/apps/hello_world/hello_world.py"
  env_vars:
    HELLO: "world"